import type { Metadata } from "next";
import localFont from "next/font/local";
import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Shared/Navbar";
import AuthProvider from "./services/AuthProvider";
import QueryProvider from '../app/QueryProvider/QueryProvider';



const outfit = Outfit({ weight: ["300", "400", "500", "700"], subsets: ["latin"] })

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Crafty Bay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="craftyBayTheme">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.className} antialiased`}
      >
        <AuthProvider>
          <QueryProvider>
            <Navbar />
            {children}
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
